import Navbar from '../ui/components/Navbar';
import './global.css';


export const metadata = {
  title: 'Welcome to apps/frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}) {

  return (
    <html lang="en">
      <body >
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
